### ISSUE TITLE
little typedef typo at videorescaler.h

### ISSUE THREAD

**Issue by blinkenlichten** [h4tr3d/avcpp#1]
Hey there! It's really great project.

```
diff --git a/src/videorescaler.h b/src/videorescaler.h
index 169eb84..085f86e 100644
--- a/src/videorescaler.h
+++ b/src/videorescaler.h
@@ -55,8 +55,8 @@ private:
 
 };
 
-typedef std::shared_ptr<VideoRescaler> VideoResamplerPtr;
-typedef std::weak_ptr<VideoRescaler> VideoResamplerWPtr;
+typedef std::shared_ptr<VideoRescaler> VideoRescalerPtr;
+typedef std::weak_ptr<VideoRescaler> VideoRescalerWPtr;
 
 } // ::av
```

**Comment by h4tr3d** [comment]
Yeh, it is first feed back, thanks :-)

Also, I recommend to try api-2 branch. But currently it works only for Video.

**Comment by blinkenlichten** [comment]
Okay, I'm going to give it a try. Seems that same patch is needed for the api-2 branch.
The conflict of typedefs remains there when both videorescaler.h and videoresampler.h included.
