### ISSUE TITLE
[feature] Allow linear video editing

### ISSUE THREAD

**Issue by Adenilson** [h4tr3d/avcpp#13]
It is quite common for people to use ffmpeg to cut videos, as detailed on:
https://trac.ffmpeg.org/wiki/Seeking

It would be awesome for avcpp to support a similar feature. Ideally, the user could just pass the starting point in the video and the duration of the section.

**Comment by h4tr3d** [comment]
Hi!
Could you please check latest master code? I add seek() interface to the FormatContext: a95e2355b22efa7a5c4b8a04188c2d3bcd7b819e
