### ISSUE TITLE
Error when using code from api2-remux.cpp sample.

### ISSUE THREAD

**Issue by akochkarev** [h4tr3d/avcpp#130]
Hello!

I am trying to adapt this sample (api2-remux.cpp) for truncating audio files to needed duration without reencoding.

But facing next issue:
When coping streams 
```cpp
       // copy codec settings
        ocoder.copyContextFrom(icoder);
```
exception arises: "Codec context invalid" 
and log says: 
[NULL @ 0x562aaeddb780] copyContextFrom: Invalid target context

Log:
```
[wav @ 0x562aaed89fc0] Opening 'test.wav' for reading
[file @ 0x562aaed8b840] Setting default whitelist 'file,crypto,data'
[wav @ 0x562aaed89fc0] Before avformat_find_stream_info() pos: 80 bytes read:32768 seeks:0 nb_streams:1
[wav @ 0x562aaed89fc0] parser not found for codec pcm_f32le, packets or times may be invalid.
[wav @ 0x562aaed89fc0] parser not found for codec pcm_f32le, packets or times may be invalid.
[wav @ 0x562aaed89fc0] max_analyze_duration 5000000 reached at 5120000 microseconds st:0
[wav @ 0x562aaed89fc0] After avformat_find_stream_info() pos: 176208 bytes read:196608 seeks:0 frames:42
Input #0, wav, from 'test.wav':
  Duration: 00:00:14.45, bitrate: 256 kb/s
  Stream #0:0, 42, 1/8000: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 8000 Hz, 1 channels, flt, 256 kb/s
[NULL @ 0x562aaeddb780] copyContextFrom: Invalid target context
terminate called after throwing an instance of 'av::Exception'
  what():  Codec context invalid
 ```
 
 Any ideas, what can be wrong here?
 Thanks!

**Comment by h4tr3d** [comment]
Will look today

**Comment by h4tr3d** [comment]
@akochkarev , could you please check latest master code?

**Comment by akochkarev** [comment]
@h4tr3d , thanks for response!

I've tested api2-remux.cpp example from latest sources from master today.
And now it works good.

But I see that there some new methods like Stream::codecParameters() was added and this breaks compatibility with v2.2.1 which I use from vcpkg currently.

Waiting for new release :)
Thanks for a cool project!

**Comment by h4tr3d** [comment]
Oops... vcpkg... I forgot about them.

**Comment by h4tr3d** [comment]
More details are needed.
