### ISSUE TITLE
How to just use avcpp to write externally compressed data into an output stream?

### ISSUE THREAD

**Issue by irieger** [h4tr3d/avcpp#133]
Hey,

I'm currently playing with some codec development to better understand how things are working in this area. Now that I have encoding and decoding working, I'd like to create some files to see how it looks to regular software.

For the decoding, I just open a mov for example roughly following the demux example, seeking a frame I want decoded and then just readPacket it from the context. This works well already and I'd basically want to do the same now in the other direction. Just create a container and set the necessary information and then add the packet for each frame.

Can't really fit things together just based on the examples and docu. Mainly I'm trying to understand how I create a stream that has the relevant data without giving it a codec. Something like "create me a video stream & set this FourCC identifier and whatever elese is needed". Is there something to go by that I'm missing? Any example etc.?

Cheers,
Ingmar

P.S. I really like avcpp so far. Before I worked just a bit directly via ffmpeg/libav and I'm not really that much of a fan for such old style interfaces.

**Comment by h4tr3d** [comment]
Move to Discussion sections instead of Issue one,
