### ISSUE TITLE
Why are all the video frames in the output marked as I-frames？

### ISSUE THREAD

**Issue by luyoi1** [h4tr3d/avcpp#136]
![image](https://github.com/h4tr3d/avcpp/assets/121417852/a2fc1e03-9043-47e6-90c0-11e01833ad57)
Why is the picture type set to AV_PICTURE_TYPE_I for all frames here?
In my case, the encoder would encode the entire video stream into I-frames using this picture type

**Comment by h4tr3d** [comment]
Please, do  not use images for the code listings. And move to the Discussion instead Issues
