### ISSUE TITLE
Get codec information from stream?

### ISSUE THREAD

**Issue by rajkosto** [h4tr3d/avcpp#14]
I'm doing simple remux and replaced raw ffmpeg with your library but couldnt find a way to do this without accessing raw() ?

```
		const auto srcVideoStream = formatCtx.stream(videoStream).raw();
		videoOutStream = outCtx.addStream(av::Codec(srcVideoStream->codec->codec));
		if (outCtx.outputFormat().isFlags(AVFMT_GLOBALHEADER))
			videoOutStream.raw()->codec->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;

		videoOutStream.setTimeBase(srcVideoStream->codec->time_base);
```

Also doing outCtx.dump() gives me     Stream #0:0: Unknown: none So not sure if i even did that correctly ?

**Comment by h4tr3d** [comment]
Hi!
Could you please check latest master and look into api2-remux.cpp sample?

**Comment by h4tr3d** [comment]
Done: d5f59e684e134984e04b8e8669f02f99c75bf27f
