### ISSUE TITLE
Question about FFWrapperPtr

### ISSUE THREAD

**Issue by algebrato** [h4tr3d/avcpp#142]
About line:
https://github.com/h4tr3d/avcpp/blob/82facd4beb0ebc87b67400b461f362254dd9c9f9/src/ffmpeg.h#L68

am wodering why do you implement this template struct instead using `std::unique_ptr` ? As far as i understand, it does the same things

**Comment by h4tr3d** [comment]
No. It provides on-owned wrapping for core pointer. It is not a best solution here. But sounds like it just work for now.
