### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by leavittx** [h4tr3d/avcpp#21]
Hi! I wonder whether the examples are supposed to work in the master branch.
I'm trying the api2-decode-encode-video.cpp

There might be a problem in the Stream::mediaType() method,
since m_raw->codecpar doesn't seem to contain valid data, while m_raw->codec has it, but the former is chosen by preprocessor directive.

Additionally I don't see code where you set the width/height/pix_fmt fields of AVStream's codec/codecpar. Having these unset causes an error like this:
[mp4 @ 000001bae753ba00] dimensions not set
while calling octx.writeHeader(); line of api2-decode-encode-video.cpp

I want to use avcpp in my project and willing to contribute the hardware-accelerated encoding code, but with these basic problems it might not be possible. Am I doing something wrong?

Libavformat version 57.66.102, target platform Windows 10 64-bit (visual studio toolchain is used)

**Comment by h4tr3d** [comment]
> since m_raw->codecpar doesn't seem to contain valid data, while m_raw->codec has it, but the former is chosen by preprocessor directive.
Stupid FFmpeg upstream make warning on access to the m_raw->codec

> Additionally I don't see code where you set the width/height/pix_fmt fields of AVStream's codec/codecpar. 

For input streams it filled by FFmpeg. For output streams it filled by FFmpeg too using codec parameters (as I know). I try to check ASAP.

**Comment by leavittx** [comment]
Thanks, that would be awesome! You think the problem is with the ffmpeg version? (also see #22)

**Comment by h4tr3d** [comment]
I think that FFmpeg deprecate API but still use it internally in some codecs/formats and not fully migrate to new one, but annoying warning is added... It currently safe to use old API: it will be removed completely only in FFmpeg 4.

**Comment by leavittx** [comment]
I'm using libx264 in my project. Guess it should be updated to use the new API already!

api2-decode-encode-video.cpp still seem to be unworkable due to unset dimensions and probably some additional stuff I haven't found out yet. Do you need any additional info from my side?

**Comment by JegernOUTT** [comment]
I have same problems with Stream::mediaType() method. How can I manually switch to the old ffmpeg / avcpp API? Is there any #define macros or cmake variables in cmake files?

**Comment by h4tr3d** [comment]
Guys, could you please check 8b8255d?

**Comment by ShikinChen** [comment]
codecpar->codec_type is AVMEDIA_TYPE_UNKNOWN, because avformat_new_stream param codec not use on FFmpeg 5.0,codecpar->codec_type is avcodec_parameters_alloc() , no param on codecpar->codec_type

**Comment by h4tr3d** [comment]
@ShikinChen, sounds like initialization sequence must be reworked completely from the AvCpp side for the new versions of the FFmpeg.
