### ISSUE TITLE
SIGABRT when FormatContext destructor called

### ISSUE THREAD

**Issue by JegernOUTT** [h4tr3d/avcpp#23]
**Stacktrace:**
![2017-04-10 14-46-25](https://cloud.githubusercontent.com/assets/9404669/24860282/89b7dffe-1dfc-11e7-86da-5e3fa348174b.png)

**Encoder function body:**
https://pastebin.com/JwHeTAc3

If you need more info, i'm ready to provide it

**Comment by h4tr3d** [comment]
Look like double free. Could you please re-build FFmpeg with debug information?

**Comment by h4tr3d** [comment]
@JegernOUTT, hi, could you please provide minimal work sample to issue reproduce?

**Comment by h4tr3d** [comment]
@JegernOUTT  is issue still actual and reproducible?

**Comment by h4tr3d** [comment]
No feedback
