### ISSUE TITLE
Can't add subtitles stream to mkv

### ISSUE THREAD

**Issue by rkfg** [h4tr3d/avcpp#24]
I'm using Debian Stretch amd64, libavformat 57.
[These lines](https://github.com/h4tr3d/avcpp/blob/a2be4c78fe91535498e956b089ef12cc4b5e60e5/src/formatcontext.cpp#L208) block adding a subtitles stream. I can form a valid H264+Vorbis stream packed to MKV but can't add subtitles due to that support check. MKV indeed supports subtitles but the check says otherwise. It could be an ffmpeg bug or something with my local setup. I commented the check out, after that avformat_new_stream successfully adds the subtitles stream and I can encode my subs to it getting a valid MKV file.

The code is very straightforward, like this:
```cpp
        Codec sub_codec = findEncodingCodec(AV_CODEC_ID_SUBRIP);
        auto sub_stream = ofctx.addStream(sub_codec, ec);
        LOGFATAL("Can't add subtitles stream")
        subctx.openInput(argv[4], ec);
        LOGFATAL("Can't open subtitles")
        subctx.findStreamInfo(ec);
        LOGFATAL("No subtitles streams found")

        ofctx.dump();
        ofctx.writeHeader();
        ofctx.flush();

        while (true) {
            auto pkt = subctx.readPacket(ec);
            if (pkt.isNull()) {
                break;
            }
            LOGERR("Packet reading error")
            pkt.setStreamIndex(2);
            ofctx.writePacket(pkt, ec);
            LOGERR("Packet writing error")
        }
```
I think we shouldn't explicitly check for stream support and instead rely on avformat_new_stream returning NULL on error.

**Comment by rkfg** [comment]
I'm rebasing my branch with some patches so this issue gets spammed. Anyway, it seems something inside libav is not behaving properly. Either MKV is not well-defined in terms of supported formats or `av_codec_get_tag2` should not be used [like that](https://github.com/h4tr3d/avcpp/blob/a2be4c78fe91535498e956b089ef12cc4b5e60e5/src/format.cpp#L14). Maybe it doesn't support getting tags for subtitle streams, I have no idea really. The fact is, it prevents adding aubtitles to an MKV container and it's wrong so I removed that check. It's redundant anyway because right after adding a stream we check the result for NULL, so if it didn't work for whatever reason we'd `throw_if`.

**Comment by h4tr3d** [comment]
Do you use libav? What is happen if you just replace it with ffmpeg? ;-)

**Comment by rkfg** [comment]
Uhh, no, I'm using the mainstream FFmpeg. The problem is googling the information about the C API that's also called ffmpeg as the CLI utility (which is far more popular). So I usually use libav in queries and the result is mostly what I need.
