### ISSUE TITLE
clear_if() is broken on newer compilers with optimizations on

### ISSUE THREAD

**Issue by rkfg** [h4tr3d/avcpp#25]
This issue is pretty weird, it happens only when optimizations are on (-O1, -O2, -O3, -Os etc.) and on G++ 6 and up and clang++ 3.5 at least. G++ 5 works fine. So, here's a minimal example:
```cpp
#include <iostream>
#include <system_error>

using namespace std;

error_code& throws() {
  return *((error_code*)0);
}

void clear_if(error_code& ec) {
  error_code& ec_local = throws();
  cout << &ec << " / " << &throws() << " / " << &ec_local << endl;
  if (&ec != &throws()) {
    cout << "&ec != &throws()" << endl;
  } else {
    cout << "&ec == &throws()" << endl;
  }
  if (&ec != &ec_local) {
    cout << "&ec != &ec_local" << endl;
  } else {
    cout << "&ec == &ec_local" << endl;
  }
  if (&ec_local != &throws()) {
    cout << "&ec_local != &throws()" << endl;
  } else {
    cout << "&ec_local == &throws()" << endl;
  }
  if (&ec == 0) {
    cout << "&ec == 0" << endl;
  } else {
    cout << "&ec != 0" << endl;
  }
  if (&ec != 0) {
    cout << "&ec != 0" << endl;
  } else {
    cout << "&ec == 0" << endl;
  }
  if (&ec_local == 0) {
    cout << "&ec_local == 0" << endl;
  } else {
    cout << "&ec_local != 0" << endl;
  }
  if (&ec_local != 0) {
    cout << "&ec_local != 0" << endl;
  } else {
    cout << "&ec_local == 0" << endl;
  }
}

int main() {
  clear_if(throws());
  return 0;
}
```

I tried to compile it with the following commands and checked the output:
> g++-5 -O0 -std=c++11 test.cpp
```
0 / 0 / 0
&ec == &throws()
&ec == &ec_local
&ec_local == &throws()
&ec == 0
&ec == 0
&ec_local == 0
&ec_local == 0
```
> g++-6 -O0 -std=c++11 test.cpp
```
0 / 0 / 0
&ec == &throws()
&ec == &ec_local
&ec_local == &throws()
&ec == 0
&ec == 0
&ec_local == 0
&ec_local == 0
```
> g++-5 -O1 -std=c++11 test.cpp
```
0 / 0 / 0
&ec == &throws()
&ec == &ec_local
&ec_local == &throws()
&ec == 0
&ec == 0
&ec_local == 0
&ec_local == 0
```
> g++-6 -O1 -std=c++11 test.cpp
```
0 / 0 / 0
&ec != &throws()
&ec != &ec_local
&ec_local == &throws()
&ec == 0
&ec != 0
&ec_local == 0
&ec_local == 0
```
> clang++ -O0 -std=c++11 test.cpp
```
0 / 0 / 0
&ec == &throws()
&ec == &ec_local
&ec_local == &throws()
&ec == 0
&ec == 0
&ec_local == 0
&ec_local == 0
```
> clang++ -O1 -std=c++11 test.cpp
```
0 / 0 / 0
&ec != &throws()
&ec != &ec_local
&ec_local == &throws()
&ec != 0
&ec != 0
&ec_local != 0
&ec_local != 0
```
I suspect making a null reference is an undefined behavior and that's why it breaks. Note, that only null reference arguments get borked somehow, local variables are compared just fine. Still, UB is UB and we shouldn't rely on it. As you can see, &ec both equals and not equals zero, it's undefined. The first branch is always executed as the condition is always true.

The exact issue in avcpp is that [this line](https://github.com/h4tr3d/avcpp/blob/master/src/averror.h#L211) is executed while ec is a null reference that causes a segfault if the library is compiled with G++ 6 and up in a release configuration (which usually assumes -O3).

**Comment by h4tr3d** [comment]
Thanks for report, I plan to rework this place in near future.
