### ISSUE TITLE
Problems with current version, moving from older avcpp 1.0 version

### ISSUE THREAD

**Issue by mediabuff** [h4tr3d/avcpp#30]
Hi,
I am upgrading to the latest version. It looks like  Timestamp replace TimeStamp. Now I get lipsync problems with my video player.

**Comment by h4tr3d** [comment]
Hi @mediabuff!

Sorry for delay, just have no time :-( Could you please provide sample sample that shows issue? It just simplify investigating.

**Comment by h4tr3d** [comment]
Reopen, if issue still actual.
