### ISSUE TITLE
How to use avcodec_receive_frame?

### ISSUE THREAD

**Issue by NickolayKabash** [h4tr3d/avcpp#43]
I have a simple app with this decoding method:

          ```
          static int decode(AVCodecContext *avctx, AVFrame *frame, int *got_frame, AVPacket *pkt)
          {
          int ret;
          *got_frame = 0;
          if (pkt) 
          {
                    ret = avcodec_send_packet(avctx, pkt);
                    if (ret < 0) 
                    {
                              return ret == AVERROR_EOF ? 0 : ret;
                    }
          }
          ret = avcodec_receive_frame(avctx, frame);
          if (ret < 0 && ret != AVERROR(EAGAIN) && ret != AVERROR_EOF) 
          {
                    return ret;
          }
          if (ret >= 0)
          {
                    *got_frame = 1;
          }
          return 0;
          }

I use this method to store video clip but there are a few frames in the video clip with errors or 'miss frames' from previous clip. 

avcodec_receive_frame(avctx, frame); - returns code '-11' that stands for 'other negative values: legitimate decoding errors'. What the 'other negative values' are?

**Comment by h4tr3d** [comment]
Sorry for delay. Just reference to official docs:
- https://ffmpeg.org/doxygen/trunk/group__lavc__decoding.html#ga11e6542c4e66d3028668788a1a74217c
- https://ffmpeg.org/doxygen/trunk/group__lavc__decoding.html#ga58bc4bf1e0ac59e27362597e467efff3

and new send/receive API overview:
- https://ffmpeg.org/doxygen/3.3/group__lavc__encdec.html

In short: all (or most) codecs has "delay": count of frames/packet that should be pushed to the codec before first packet/frame received. Obviously, codec context has some queue. So, when pipeline restarts, you must flush this queue by sending some special data.
