### ISSUE TITLE
play control

### ISSUE THREAD

**Issue by w136111526** [h4tr3d/avcpp#46]
I want to play the video at twice the speed. can I use this project?

**Comment by h4tr3d** [comment]
To increase/decrease playback speed you just must decrease/increase sleep time between readed frames. So, you can use any project for it. FFmpeg itself, AvCpp and so on.

See: https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video this solution uses filters. Currently filters support in AvCpp not so much pretty.

**Comment by w136111526** [comment]
Hello, I 've seen the ffmpeg document you recommended for me, but I still don't know how to use the filter in my C++ code. Do you mean I must create a filter and add it to the video stream，or add it to the video decoded?

**Comment by h4tr3d** [comment]
Filters works with uncompressed frames. Pipeline should look like:
input_format -> decored ->[filter graph sink] filter graph [filter graph src]->encoder->output_format

In current implementation I suggest to use native FFmpeg API to create and manipulate with Filter Graphs.

**Comment by h4tr3d** [comment]
Also, you can try just play with PTS in frames. If you increase PTS distance, frames will be shown slowly. If you decrease PTS distance, frames will be shown quickly.
