### ISSUE TITLE
pkg-config file include some problem

### ISSUE THREAD

**Issue by cherryunix** [h4tr3d/avcpp#49]
Hi,
    i found that libavcpp.pc file have a mistake in includedir,it is `includedir = ${prefix}/include` now.In this situation,we cant include header file directly like the way in example `#include "av.h"` instead of `#include "avcpp/av.h"`
  could you please fix this problem,or im very glad to fix it
  sorry im not a native english speaker.....

**Comment by h4tr3d** [comment]
> i found that libavcpp.pc file have a mistake in includedir,it is includedir = ${prefix}/include now.

Work as designed. I do it to avoid possible conflicts with names.

>  sorry im not a native english speaker.....
Same case :-D

**Comment by cherryunix** [comment]
sorry,didn't mention conflicts problem before
