### ISSUE TITLE
ffmpeg package issues

### ISSUE THREAD

**Issue by xixihao123** [h4tr3d/avcpp#52]
Hello, I want to compile avcpp in Windows. Can you support the PkgConfig module lookup for Windows FFmpeg? cmake tool reported wrong:

Call Stack (most recent call first):
CMake Error at cmake/FindFFmpeg.cmake:186 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)
CMake Error at D:/develop/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FFmpeg (missing: FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS
  AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS AVFORMAT_LIBRARIES
  AVFORMAT_INCLUDE_DIRS AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS
  AVDEVICE_LIBRARIES AVDEVICE_INCLUDE_DIRS AVFILTER_LIBRARIES
  AVFILTER_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS
  SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS)
Call Stack (most recent call first):
  D:/develop/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFmpeg.cmake:204 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)

**Comment by h4tr3d** [comment]
Hi, 
Currently, PkgConfig uses anywhere if found:
https://github.com/h4tr3d/avcpp/blob/master/cmake/FindFFmpeg.cmake#L94

Unfortunately, I have no ability to check building under Windows. For now, I tried to build AvCpp for Windows only using MingGW and MXE.

In any case, what do you use to build AvCpp? Visual Studio? MinGW? If you use MinGW, you must set proper cmake generator (see cmake's `-G` option).

**Comment by xixihao123** [comment]
Hello, when I used vs. 2015, when I used FFmpeg, the environment variable also added C: \ MinGW \ FFmpeg, but I couldn't find the FFmpeg package.

**Comment by xixihao123** [comment]
![image](https://user-images.githubusercontent.com/45343237/59080625-55052180-891c-11e9-9bb1-af631feb440a.png)

**Comment by xixihao123** [comment]
![image](https://user-images.githubusercontent.com/45343237/59080647-664e2e00-891c-11e9-8aed-aa250374b58f.png)

**Comment by h4tr3d** [comment]
Hmm... I am not sure, but seems that you try to mix VS compiler and MinGW libraries... 

You should download DEV version of builded FFmpeg from https://ffmpeg.zeranoe.com/builds/ that contains both libraries for MinGW and for VS. And setup VS to refer them.

During AvCpp build you should point right CMake generator (use CMake option `-G xxx`, where `xxx` may be "NMake Makefiles") and FFmpeg search hints (see file https://github.com/h4tr3d/avcpp/blob/master/cmake/FindFFmpeg.cmake), for example:
```
mkdir build
cd build
cmake -G "NMake Makefiles" -DPC_FFMPEG_LIBRARY_DIRS=D:/dev/ffmpeg/lib -DPC_FFMPEG_INCLUDE_DIRS=D:/dev/ffmpeg/include ..
```

I have no Windows and VS installations near me, so I can't check solution above. But I know that some guys successfully built AvCpp with VS.
