### ISSUE TITLE
VideoFrame data-constructor only uses first row of source image data

### ISSUE THREAD

**Issue by Silverlan** [h4tr3d/avcpp#53]
I've tried writing a simple video encoder with the source image data being read from a buffer in memory, but I've noticed that it would only encode the very first row of my image data and the rest would be black.
After inspecting the source code, I've noticed this in the constructor for _VideoFrame_:
```
VideoFrame::VideoFrame(const uint8_t *data, size_t size, PixelFormat pixelFormat, int width, int height, int align)
{
    [...]
    for (size_t i = 0; i < 4 && buf[i]; ++i) {
        std::copy(buf[i], buf[i]+linesize[i], m_raw->data[i]);
    }
}
```
I'm new to ffmpeg, but this looks wrong to me. _linesize_ only contains the size of a single row, so this would only copy the very first row from the source buffer, which would explain what I got as a result.

As a test, I've tried overwriting the data manually (memcpy) after creating the frame:
```
auto width = encoder.width();
auto height = encoder.height();
using Color = std::array<uint8_t,3>;
std::vector<Color> colors {};
colors.resize(width *height,Color{0,255,255});

auto pxFormatRGB = AVPixelFormat::AV_PIX_FMT_RGB24;
uint32_t alignment = 32u;
av::VideoFrame frame{reinterpret_cast<uint8_t*>(colors.data()),colors.size() *sizeof(colors.front()),pxFormatRGB,static_cast<int32_t>(width),static_cast<int32_t>(height),static_cast<int32_t>(alignment)};

memcpy(frame.raw()->data[0],colors.data(),colors.size() *sizeof(colors.front()));
frame.raw()->pts = 0;
frame.raw()->pkt_dts = 0;
frame.setComplete(true);
```
This is just a dirty work-around (and doesn't take any line padding into account), but it fixed the issue for my test case. I'm still mostly unfamiliar with ffmpeg, so I haven't created a pull request, since I'm not sure what a proper fix would be. Or maybe I just did something wrong altogether and this is not actually a bug?

**Comment by h4tr3d** [comment]
@Silverlan hi and thanks for report!

Could you please try last trunk commit (referenced above)?
