### ISSUE TITLE
FormatContext::openInput(CustomIO, OptionalErrorCode, size_t) is not implemented

### ISSUE THREAD

**Issue by heshuimu** [h4tr3d/avcpp#54]
I tried to call this function but the linker says symbol not found. I was not able to find the implementation of this function in the cpp file either. 
https://github.com/h4tr3d/avcpp/blob/a1fef2ac371cc937f52131e877b8e9855ba08a67/src/formatcontext.h#L125-L127

PS. Is this a good workaround?
```cpp
av::FormatContext inputContext;
inputContext.openInput(&customIO, av::InputFormat());
```

**Comment by h4tr3d** [comment]
Yep. My mistake. Will fix ASAP. Suggested WA is worked.
