### ISSUE TITLE
recursive cloning

### ISSUE THREAD

**Issue by nestyme** [h4tr3d/avcpp#55]
Hello!
Firstly thanks a lot for a great work. 
I have a little remark -- I think git cloning should be made in recursive way to clone catch2, isn't It?
Otherwise during cmake It will crash in some cases and give something like
-- /root/avcpp-git/catch2/contrib

> CMake Error at tests/CMakeLists.txt:20 (include):
>   include could not find load file:
> 
>     Catch

Best regards,
Nadya

**Comment by h4tr3d** [comment]
Nadya, thanks. Catch2 connected as submodule, so `git submodule init && git submodule update` actions are required (or `git clone --recurse-submodules -j8 ...` with moder Git). I just forgot to add this into README.

BTW:
>  -- /root/avcpp-git/catch2/contrib

Do not work / build under root ;-)

**Comment by nestyme** [comment]
> Nadya, thanks. Catch2 connected as submodule, so `git submodule init && git submodule update` actions are required (or `git clone --recurse-submodules -j8 ...` with modern Git). I just forgot to add this into README.
> 
> BTW:
> 
> > -- /root/avcpp-git/catch2/contrib
> 
> Do not work / build under root ;-)

It's inside dockerfile)

**Comment by h4tr3d** [comment]
> It's inside docker)
А! Ему можно :)
