### ISSUE TITLE
Using multiple audio Resamplers on the same stream

### ISSUE THREAD

**Issue by memento87** [h4tr3d/avcpp#70]
What I want to do:

`
Packet pkt = ictx.readPacket(ec);
AudioSamples samples = running->adec->decode(pkt, ec);

resampler1.push(samples);
resampler2.push(samples);
resampler3.push(samples);
`

Where each of those resamplers is configured to a different sampling rate and sample format.
I tried cloning the samples before feeding them into the resampler, still not working.

Is that at all possible?

**Comment by memento87** [comment]
Actually it does work. I probably had some error in my own code. Sorry for bringing this up. Cheerz.

**Comment by h4tr3d** [comment]
Hello! Don't worry!
