### ISSUE TITLE
save avpack raw data into h264 file, but it can't play,help!

### ISSUE THREAD

**Issue by jcyhcs** [h4tr3d/avcpp#86]
![image](https://user-images.githubusercontent.com/34532224/100070188-97a21d00-2e74-11eb-933f-b87829ea4299.png)
container is FLV, how can i save raw h264 file?

**Comment by h4tr3d** [comment]
Don't write raw h264 data to the file. Try to use h264 muxer.

**Comment by h4tr3d** [comment]
Sample, that works for me:
```c++
#include <iostream>

#include "av.h"
#include "format.h"
#include "codeccontext.h"
#include "formatcontext.h"

using namespace std;

int main(int argc, char** argv)
{
    if (argc < 3)
        return 2;

    string input_uri{argv[1]};
    string output_uri{argv[2]};

    av::init();

    //
    // INPUT
    //
    av::FormatContext ictx;

    ictx.openInput(input_uri);
    ictx.findStreamInfo();

    ssize_t video_stream = -1;

    //
    // OUTPUT
    //
    av::OutputFormat oformat("h264");
    av::FormatContext octx;
    octx.setFormat(oformat);

    for (size_t i = 0; i < ictx.streamsCount(); ++i) {
        auto st = ictx.stream(i);
        auto coder = av::GenericCodecContext(st);

        if (!st.isVideo())
            continue;

        if (!octx.outputFormat().codecSupported(coder.codec()))
            continue;

        auto ost = octx.addStream(coder.codec());
        ost.setTimeBase(st.timeBase());
        auto ocoder = av::GenericCodecContext(ost);

        ocoder.copyContextFrom(coder);

        video_stream = i;
        break;
    }

    clog << "VideoStream: " << video_stream << '\n';

    octx.openOutput(output_uri);
    octx.writeHeader();
    octx.dump();

    while (true) {
        auto pkt = ictx.readPacket();
        if (!pkt)
            break;

        if (pkt.streamIndex() != video_stream)
            continue;

        pkt.setStreamIndex(0);
        octx.writePacket(pkt);
    }

    octx.writePacket();
    octx.writeTrailer();

    return 0;
}
```

**Comment by jcyhcs** [comment]
one more question, i want to get  raw h264 packet , then send to HARDWARE DECODER, but if use your example, how can realize this function?  i try some code like this:
![image](https://user-images.githubusercontent.com/34532224/100181332-ee5f3380-2f14-11eb-9bee-b48436614b04.png)
i just test my code is ok,it can create h264 file, and it can play, and the raw packet can send to hardware decoder. BUT, it this code RIGHT?  it this code have memory leak??  PLEASE HELP ME!

**Comment by h4tr3d** [comment]
Just read about format of h264 packets and difference between Annex-B format and AVCC format. Start from [here](https://stackoverflow.com/questions/23404403/need-to-convert-h264-stream-from-annex-b-format-to-avcc-format). 

Basically, AVPacket contains NALU without `[start code]`. I deeply work only with Xilinx VCU via OpenMAX interface. This decoder expects packets in AnnexB format with start codes.

FFmpeg "h264" format saves frames into container in AnnexB format. You can do it manually by prepend 0x01000000 to the `pkt.data()`.

Similar things done by BSF (bitstream filter) that used by your last sample.

By my opinion, it is not a good idea to use same AVPacket pointer to receive processed packets from bistream filter chain.
