### ISSUE TITLE
Debugging the library

### ISSUE THREAD

**Issue by A2va** [h4tr3d/avcpp#97]
Hello! I build and install avcpp with success but now I want to develop but I not found how to debug the source code. So how can I debug the library ? And maybe the step to debug/contribute can added to the Readme ?

**Comment by h4tr3d** [comment]
Hi!

> So how can I debug the library?

Yes, like any other software. Use samples and tests as a runnable wrappers, write your own one.

> And maybe the step to debug/contribute can added to the Readme?

I see no reasons for it. Just do changes that you need and that maybe useful to others and do GitHub Pull Request. I look into it and Approve or Deny
